/*
 * rxgk_err.h:
 * This file is automatically generated; please do not edit it.
 */

#include <et/com_err.h>

#define RXGKINCONSISTENCY                        (1233242880L)
#define RXGKPACKETSHORT                          (1233242881L)
#define RXGKLEVELFAIL                            (1233242882L)
#define RXGKTICKETLEN                            (1233242883L)
#define RXGKOUTOFSEQUENCE                        (1233242884L)
#define RXGKNOAUTH                               (1233242885L)
#define RXGKBADKEY                               (1233242886L)
#define RXGKBADTICKET                            (1233242887L)
#define RXGKUNKNOWNKEY                           (1233242888L)
#define RXGKEXPIRED                              (1233242889L)
#define RXGKSEALEDINCON                          (1233242890L)
#define RXGKDATALEN                              (1233242891L)
#define RXGKILLEGALLEVEL                         (1233242892L)
#define RXGKWRONGVERS                            (1233242893L)
#define RXGKNOSECDATA                            (1233242894L)
#define RXGKBADCKTYPE                            (1233242895L)
#define RXGKCKSUMLEN                             (1233242896L)
extern const struct error_table et_RXGK_error_table;
extern void initialize_RXGK_error_table(void);

/* For compatibility with Heimdal */
extern void initialize_RXGK_error_table_r(struct et_list **list);

#define ERROR_TABLE_BASE_RXGK (1233242880L)

/* for compatibility with older versions... */
#define init_RXGK_err_tbl initialize_RXGK_error_table
#define RXGK_err_base ERROR_TABLE_BASE_RXGK
